package kr.co.sist.web.member;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class Main extends HttpServlet {
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.setContentType("text/html;charset=UTF-8");
		PrintWriter out=response.getWriter();
	     out.write("<!DOCTYPE html>\r\n");
	      out.write("<html>\r\n");
	      out.write("<head>\r\n");
	      out.write("<meta charset=\"UTF-8\">\r\n");
	      out.write("<title>Insert title here</title>\r\n");
	      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://211.63.89.140:8080/servlet_prj/common/css/main.css\"/>\r\n");
	      out.write("<!--  CDN -->\r\n");
	      out.write("<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
	      out.write("<!-- SmartMenus core CSS (required) -->\r\n");
	      out.write(" <link href=\"common/js/smart/css/sm-core-css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	      out.write("<link href=\"common/js/smart/css/sm-simple/sm-simple.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	      out.write("<!-- SmartMenus jQuery plugin -->\r\n");
	      out.write("<script type=\"text/javascript\" src=\"common/js/smart/jquery.smartmenus.min.js\"></script>\r\n");
	      out.write("<script type=\"text/javascript\">\r\n");
	      out.write("function chkNull(){\r\n");
	      out.write("\tif($(\"#id\").val()==\"\"){\r\n");
	      out.write("\t\t$(\"#id\").focus();\r\n");
	      out.write("\t\treturn;\r\n");
	      out.write("\t}//end if\r\n");
	      out.write("\tif($(\"#passwd\").val()==\"\"){\r\n");
	      out.write("\t\t$(\"#passwd\").focus();\r\n");
	      out.write("\t\treturn;\r\n");
	      out.write("\t}//end if\r\n");
	      out.write("\t$(\"[name='frm']\").submit();\r\n");
	      out.write("}//chkNull\r\n");
	      out.write("\r\n");
	      out.write("$(function() {\r\n");
	      out.write("\t$('#main-menu').smartmenus({\r\n");
	      out.write("\t\tsubMenusSubOffsetX: 1,\r\n");
	      out.write("\t\tsubMenusSubOffsetY: -8\r\n");
	      out.write("\t});//smartmenus\r\n");
	      out.write("\t$(\"#id\").keydown(function(evt) {\r\n");
	      out.write("\t\tif( evt.which ==13 ){\r\n");
	      out.write("\t\t\tchkNull();\r\n");
	      out.write("\t\t}//end if\r\n");
	      out.write("\t});//keydown\r\n");
	      out.write("\t$(\"#passwd\").keydown(function(evt) {\r\n");
	      out.write("\t\tif( evt.which ==13 ){\r\n");
	      out.write("\t\t\tchkNull();\r\n");
	      out.write("\t\t}//end if\r\n");
	      out.write("\t});//keydown\r\n");
	      out.write("\t$(\".btn\").click(function(){\r\n");
	      out.write("\t\tchkNull();\r\n");
	      out.write("\t});\r\n");
	      out.write("\t\r\n");
	      out.write("});//ready\r\n");
	      out.write("</script>\r\n");
	      out.write("<style type=\"text/css\">\r\n");
	      out.write("#wrap { width: 1024px; height: 1000px; margin: 0px auto }\r\n");
	      out.write("#header{ height: 150px }\r\n");
	      out.write("#headerTop{ height: 75px; font-family:고딕; font-size:30px; text-align:center;\r\n");
	      out.write("\t\t\t\t\tfont-weight:bold; padding-top:25px;\r\n");
	      out.write("\t\t\tbackground: #FFF url(common/images/header_bg.png)}\r\n");
	      out.write("#navi{ height: 500px}\r\n");
	      out.write("#container{ min-height:1480px  }\r\n");
	      out.write("#footer{ height:60px;background: #FFF url(common/images/footer_bg.png) ;\r\n");
	      out.write("\t\t\tfont-size: 16px; font-weight: bold; text-align: right; \r\n");
	      out.write("\t\t\tpadding-right: 30px; padding-top:40px;\r\n");
	      out.write("\t\t\twidth: 994px;}\r\n");
	      out.write("</style>\r\n");
	      out.write("</head>\r\n");
	      out.write("<body>\r\n");
	      out.write("\t<div id=\"wrap\">\r\n");
	      out.write("\t\t<div id=\"header\">\r\n");
	      out.write("\t\t\t<div id=\"headerTop\">\r\n");
	      out.write("\t\t\t\tWeb 연습  s('. ^)v \r\n");
	      out.write("\t\t\t</div>\r\n");
	      out.write("\t\t\t<div id=\"navi\">\r\n");
	      out.write("\t\t\t    <nav id=\"main-nav\">\r\n");
	      out.write("      <!-- Sample menu definition -->\r\n");
	      out.write("     <!--  <ul id=\"main-menu\" class=\"sm sm-blue\"> -->\r\n");
	      out.write("      <ul id=\"main-menu\" class=\"sm sm-simple\">\r\n");
	      out.write("        <li><a href=\"#\">Home</a></li>\r\n");
	      out.write("        <li><a href=\"#\">파라메터연습</a>\r\n");
	      out.write("          <ul>\r\n");
	      out.write("            <li><a href=\"parameter.html\">이름이 유일할 때</a></li>\r\n");
	      out.write("            <li><a href=\"parameter_values.html\">이름이 중복될때</a></li>\r\n");
	      out.write("            <li><a href=\"#\" class=\"disabled\">사용불가</a></li>\r\n");
	      out.write("          </ul>\r\n");
	      out.write("        </li>\r\n");
	      out.write("        <li><a href=\"why_session_a.html\">세션이 필요한이유</a></li>\r\n");
	      out.write("        <li><a href=\"#\">지원</a>\r\n");
	      out.write("          <ul>\r\n");
	      out.write("            <li><a href=\"\">메뉴1</a></li>\r\n");
	      out.write("            <li><a href=\"\">메뉴2</a></li>\r\n");
	      out.write("          </ul>\r\n");
	      out.write("        </li>\r\n");
	      out.write("        \r\n");
	      out.write("        <li><a href=\"#\">메뉴3</a>\r\n");
	      out.write("          <ul class=\"mega-menu\">\r\n");
	      out.write("            <li>\r\n");
	      out.write("              <!-- The mega drop down contents -->\r\n");
	      out.write("              <div style=\"width:400px;max-width:100%;\">\r\n");
	      out.write("                <div style=\"padding:5px 24px;\">\r\n");
	      out.write("                <p>Servlet과 JSP를 만드는 목적 : 동적으로 HTML을 생성하기위해서</p>\r\n");
	      out.write("                </div>\r\n");
	      out.write("              </div>\r\n");
	      out.write("            </li>\r\n");
	      out.write("          </ul>\r\n");
	      out.write("        </li>\r\n");
	      out.write("      </ul>\r\n");
	      out.write("    </nav>\r\n");
	      out.write("\t\t\t</div>\r\n");
	      out.write("\t\t</div>\r\n");
	      out.write("\t\t<div id=\"container\">\r\n");
	      out.write("\t\t<div style=\"position: relative;\">\r\n");
	      out.write("\t\t\t<img src=\"member/images/temp_bg1.png\" style=\"position: absolute;top:0px; left:0px\"/>\r\n");
	      out.write("\t\t\t<div style=\"position: absolute;top: 30px;left:700px\">\r\n");
	      out.write("\t\t\t<form action=\"use_session_b\"  name=\"frm\" method=\"post\">\r\n");
	      out.write("\t\t\t\t<table>\r\n");
	      out.write("\t\t\t\t\t<tr>\r\n");
	      out.write("\t\t\t\t\t\t<td>\r\n");
	      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"id\" class='inputBox'\r\n");
	      out.write("\t\t\t\t\t\t\tplaceholder=\"아이디\" id=\"id\" \r\n");
	      out.write("\t\t\t\t\t\t\tautofocus=\"autofocus\" tabindex=\"1\"\r\n");
	      out.write("\t\t\t\t\t\t\tstyle=\"width:200px;height: 30px\"/>\r\n");
	      out.write("\t\t\t\t\t\t</td>\r\n");
	      out.write("\t\t\t\t\t\t<td rowspan=\"2\">\r\n");
	      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"로그인\"\t\r\n");
	      out.write("\t\t\t\t\t\t\t\ttabindex=\"3\"\r\n");
	      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn\" style=\"height: 66px;width: 65px\"/>\r\n");
	      out.write("\t\t\t\t\t\t</td>\r\n");
	      out.write("\t\t\t\t\t</tr>\r\n");
	      out.write("\t\t\t\t\t<tr>\r\n");
	      out.write("\t\t\t\t\t\t<td>\r\n");
	      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"passwd\"  style=\"width:200px;height: 30px\"\r\n");
	      out.write("\t\t\t\t\t\tclass=\"inputBox\" placeholder=\"비밀번호\" id=\"passwd\"\r\n");
	      out.write("\t\t\t\t\t\ttabindex=\"2\"/>\r\n");
	      out.write("\t\t\t\t\t\t</td>\r\n");
	      out.write("\t\t\t\t\t</tr>\r\n");
	      out.write("\t\t\t\t</table>\r\n");
	      out.write("\t\t\t</form>\r\n");
	      out.write("\t\t\t\t<div>\r\n");
	      out.write("\t\t\t\t<a href=\"member/agreement.html\">회원가입</a>\r\n");
	      out.write("\t\t\t\t<a href=\"#\">아이디/비밀번호 찾기</a>\r\n");
	      out.write("\t\t\t\t</div>\r\n");
	      out.write("\t\t\t</div>\r\n");
	      out.write("\t\t</div>\r\n");
	      out.write("\t\t</div>\r\n");
	      out.write("\t\t<div id=\"footer\">\r\n");
	      out.write("\t\t\tCopyright&copy; class4 All Right Reserved.\r\n");
	      out.write("\t\t</div>\r\n");
	      out.write("\t</div>\r\n");
	      out.write("</body>\r\n");
	      out.write("</html>\r\n");
	}

}
